{
    'name': 'Sale Division',
    'version': '13.0.5.0.0',
    'summary': """ Sale Division. """,
    'description': "",
    'category': 'Sale',
    'author': 'Irfan',
    'company': 'Irfan',
    'maintainer': 'Irfan',
    'depends': ['base','account','sale','sales_team'],
    'website': '',
    'data': [
        'security/ir.model.access.csv',
        'views/sale_division_view.xml',
        'views/res_partner_view.xml',
        'views/product_view.xml',
        'views/sale_order_view.xml',
        'wizard/confirm_wizard_sale_view.xml',
        'wizard/confirm_wizard_sale_overdue.xml',
    ],
    'images': [''],
    'license': 'LGPL-3',
    'installable': True,
    'auto_install': False,
    'application': False,
}
